export const userActionTypes = {
  SET_USER_REQUEST: "SET_USER_REQUEST",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAIL: "SET_USER_FAIL",

  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",

  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAIL: "USER_PROFILE_FAIL",

  USER_FOLLOW_REQUEST: "USER_FOLLOW_REQUEST",
  USER_FOLLOW_SUCCESS: "USER_FOLLOW_SUCCESS",
  USER_FOLLOW_FAIL: "USER_FOLLOW_FAIL",

  USER_UNFOLLOW_REQUEST: "USER_UNFOLLOW_REQUEST",
  USER_UNFOLLOW_SUCCESS: "USER_UNFOLLOW_SUCCESS",
  USER_UNFOLLOW_FAIL: "USER_UNFOLLOW_FAIL",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",

  ALL_USER_REQUEST: "ALL_USER_REQUEST",
  ALL_USER_SUCCESS: "ALL_USER_SUCCESS",
  ALL_USER_FAIL: "ALL_USER_FAIL",
};
