export const userActionTypes = {
  SET_USER_REQUEST: "SET_USER_REQUEST",
  SET_USER_SUCCESS: "SET_USER_SUCCESS",
  SET_USER_FAIL: "SET_USER_FAIL",

  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAIL: "LOAD_USER_FAIL",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
};
